name: youtube_shortsclip_bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - google-auth==2.29.0
    - google-auth-oauthlib==1.2.0
    - google-auth-httplib2==0.2.0
    - google-api-python-client==2.126.0
    - gTTS==2.5.1
    - moviepy==1.0.3
    - Pillow==10.3.0
    - numpy==1.26.4
    - requests==2.31.0
